/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_cprakashagr_jni_MainActivity.h"

/* Header for class com_cprakashagr_jni_MainActivity */

JNIEXPORT jstring JNICALL Java_com_cprakashagr_jni_MainActivity_getStringFromNative(JNIEnv * env, jobject obj) {

    return (*env)->NewStringUTF(env, "Hello From JNI!");
}